version: "3"

services:
  node_docker_monitoreo:
    image: python:3.6-stretch
    ports:
      - "3000:3000"
    environment:
      - DEBUG=myapp:*
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    command: /bin/sh -c "pip install -r requirements.txt && python3 app.py"